services:
  mariadb:
    image: 'mariadb:11.2'
    container_name: jwt-auth-mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: jwt-auth
      MYSQL_USER: jwt_user
      MYSQL_PASSWORD: jwt_password
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "healthcheck.sh", "--connect", "--innodb_initialized" ]
      interval: 30s
      timeout: 5s
      retries: 3

  redis:
    image: redis:7.2-alpine
    container_name: jwt-auth-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 20s
      timeout: 5s
      retries: 3

volumes:
  mariadb_data:
    driver: local
  redis_data:
    driver: local
